apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-db-proxy
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/name: "trivy-db-proxy"
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: trivy-db-proxy
          restartPolicy: Never
          containers:
          - name: trivy-db-proxy
            image: ghcr.io/worldwideward/trivy-db-proxy:main
            imagePullPolicy: Always
            env:
            - name: ORAS_REGISTRY_HOST
              value: "myregistry.azurecr.io"
            - name: ORAS_REGISTRY_USERNAME
              value: "00000000-0000-0000-0000-000000000000"
            - name: DEBUG
              value: "False"
            - name: AZURE_WORKLOAD_IDENTITIES
              value: "True"
