---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: "trivy-db-proxy"
  annotations:
    azure.workload.identity/client-id: "<managed identity client id>"
  name: trivy-db-proxy
